### ISSUE TITLE
[JENKINS-19453] Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#6954]
<p>I am able to start slave.jar via ssh or via jnlp.<br/>
The log of the connection shows that the node is correctly started.<br/>
In a project, I have 2 main parts:</p>
<ul class="alternate" type="square">
	<li>a svn checkout</li>
	<li>a shell command to start cmake + compilation.</li>
</ul>

<p>If I launch my build, it hangs. Then, I disabled the svn checkout and leave only the shell command with a "echo hello".<br/>
If I start the build, it hangs with the following error message:</p>

<blockquote>
<p>Started by user anonymous<br/>
<span class="error">&#91;EnvInject&#93;</span> - Loading node environment variables.<br/>
Building remotely on slave_linux_64 in workspace /home/crystal/jenkins/workspace/TESTLinux<br/>
FATAL: command execution failed<br/>
java.io.IOException: Remote call on slave_linux_64 failed<br/>
	at hudson.remoting.Channel.call(Channel.java:723)<br/>
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:862)<br/>
	at hudson.Launcher$ProcStarter.start(Launcher.java:353)<br/>
	at hudson.Launcher$ProcStarter.join(Launcher.java:360)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:60)<br/>
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)<br/>
	at hudson.model.Build$BuildExecution.build(Build.java:199)<br/>
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:586)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer<br/>
	at hudson.Launcher$LocalLauncher.<init>(Launcher.java:755)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:991)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:965)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:326)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
	at java.lang.Thread.run(Thread.java:724)<br/>
Build step 'Execute shell' marked build as failure<br/>
Finished: FAILURE</p></blockquote>

<p>When I looked at the jenkins directory I configured on the slave, all the required jar are present, the workspace directory is present and the build directory is correctly created by the jenkins master. But nothing in this directory.</p>

---
<details><summary><i>Originally reported by <a title="yann collette" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ycollet">ycollet</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-19453" target="_blank">Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kohsuke Kawaguchi" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>
<li><b>reported by</b>: ycollet
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-03-11T01:57:56+00:00
<li><b>votes</b>: 5
<li><b>watchers</b>: 17
<li><b>imported</b>: 2025-11-06
</ul></i>
</details>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>:</i>
<p>We experience this issue since the migration to 1.509.2. It is being reproduced in 1.509.3 as well.<br/>
Seems that Windows JNLP slaves periodically fail into the death loop</p>

<blockquote>
<p><span class="error">&#91;EnvInject&#93;</span> - Loading node environment variables.<br/>
Building remotely on XXX in workspace C:\....<br/>
FATAL: command execution failed<br/>
java.io.IOException: Remote call on ru20-custom-codecs-farm09 failed<br/>
	at hudson.remoting.Channel.call(Channel.java:681)<br/>
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:862)<br/>
	at hudson.Launcher$ProcStarter.start(Launcher.java:353)<br/>
	at hudson.Launcher$ProcStarter.join(Launcher.java:360)<br/>
	...<br/>
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:237)<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer<br/>
	at hudson.Launcher$LocalLauncher.<init>(Launcher.java:755)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:991)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:965)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:326)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:58)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
Build step 'Execute Windows batch command' marked build as failure<br/>
Finished: FAILURE</p></blockquote>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>:</i>
<p>Update to remoting-2.32 in 1.509.4 does not solve the issue.<br/>
Seems that is is being reproduced even more frequently.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>@chotchki a particular bug was found, reproduced, and fixed. Whatever you are seeing might be related, or it might not. Better to file it separately, with whatever details can be found (steps to reproduce if possible), and link to this one.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=lil2006">lil2006</a>:</i>
<p>I got such issue on build Jenkins ver. 1.558<br/>
slave connected by jnlp<br/>
Here is stack trace:<br/>
FATAL: command execution failed<br/>
java.io.IOException: Remote call on slave_windows failed<br/>
	at hudson.remoting.Channel.call(Channel.java:731)<br/>
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:862)<br/>
	at hudson.Launcher$ProcStarter.start(Launcher.java:353)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:97)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)<br/>
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)<br/>
	at hudson.model.Build$BuildExecution.build(Build.java:198)<br/>
	at hudson.model.Build$BuildExecution.doRun(Build.java:159)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:523)<br/>
	at hudson.model.Run.execute(Run.java:1689)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:231)<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer<br/>
	at hudson.Launcher$LocalLauncher.<init>(Launcher.java:755)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:991)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:965)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:328)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
Build step 'Execute Windows batch command' marked build as failure<br/>
FATAL: Remote call on adft-temp-s failed<br/>
java.io.IOException: Remote call on adft-temp-s failed<br/>
	at hudson.remoting.Channel.call(Channel.java:731)<br/>
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:887)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:546)<br/>
	at hudson.model.Run.execute(Run.java:1689)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:231)<br/>
Caused by: java.lang.Error: Unable to load resource winp.dll<br/>
	at hudson.remoting.RemoteClassLoader.findResource(RemoteClassLoader.java:380)<br/>
	at java.lang.ClassLoader.getResource(Unknown Source)<br/>
	at org.jvnet.winp.Native.load(Native.java:84)<br/>
	at org.jvnet.winp.Native.<clinit>(Native.java:55)<br/>
	at org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java:200)<br/>
	at hudson.util.ProcessTree$Windows.<clinit>(ProcessTree.java:477)<br/>
	at hudson.util.ProcessTree.get(ProcessTree.java:336)<br/>
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:899)<br/>
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:890)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:328)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to call writeJarTo. Invalid object ID 2<br/>
	at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:75)<br/>
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)<br/>
	at hudson.remoting.RemoteClassLoader.findResource(RemoteClassLoader.java:372)<br/>
	... 17 more<br/>
Caused by: java.lang.IllegalStateException: Unable to call writeJarTo. Invalid object ID 2<br/>
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:293)<br/>
	at hudson.remoting.Request$2.run(Request.java:328)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	... 1 more</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jeebitesh">jeebitesh</a>:</i>
<p>Solution :- If you are running slave on windows VM\Server with 64 bit OS<br/>
Make sure of few things<br/>
1) You should have 32 bit JRE Installed<br/>
2) It should be default JRE - you go to configure Java and change the settings if you have 64 bit and 32 bit both change the default to 32 bit path.<br/>
3) Restart the Slave and that's it, Vola</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=svchipiga">svchipiga</a>:</i>
<p>Hi!<br/>
I have still this problem (Jenkins ver. 1.580.2):<br/>
<code><br/>
FATAL: Remote call on win7-home-premium-x86-ru-1-f8e failed<br/>
20:33:18 java.io.IOException: Remote call on win7-home-premium-x86-ru-1-f8e failed<br/>
20:33:18    at hudson.remoting.Channel.call(Channel.java:760)<br/>
20:33:18    at hudson.Launcher$RemoteLauncher.kill(Launcher.java:941)<br/>
20:33:18    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:556)<br/>
20:33:18    at hudson.model.Run.execute(Run.java:1745)<br/>
20:33:18    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)<br/>
20:33:18    at hudson.model.ResourceController.execute(ResourceController.java:89)<br/>
20:33:18    at hudson.model.Executor.run(Executor.java:240)<br/>
20:33:18 Caused by: java.lang.Error: Unable to load resource winp.dll<br/>
20:33:18    at hudson.remoting.RemoteClassLoader.findResource(RemoteClassLoader.java:381)<br/>
20:33:18    at java.lang.ClassLoader.getResource(Unknown Source)<br/>
20:33:18    at org.jvnet.winp.Native.load(Native.java:85)<br/>
20:33:18    at org.jvnet.winp.Native.<clinit>(Native.java:56)<br/>
20:33:18    at org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java:212)<br/>
20:33:18    at hudson.util.ProcessTree$Windows.<clinit>(ProcessTree.java:469)<br/>
20:33:18    at hudson.util.ProcessTree.get(ProcessTree.java:328)<br/>
20:33:18    at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:953)<br/>
20:33:18    at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:944)<br/>
20:33:18    at hudson.remoting.UserRequest.perform(UserRequest.java:121)<br/>
20:33:18    at hudson.remoting.UserRequest.perform(UserRequest.java:49)<br/>
20:33:18    at hudson.remoting.Request$2.run(Request.java:324)<br/>
20:33:18    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
20:33:18    at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
20:33:18    at java.lang.Thread.run(Unknown Source)<br/>
20:33:18    at ......remote call to yabrowser-win7-home-premium-x86-ru-1-f8e(Native Method)<br/>
20:33:18    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)<br/>
20:33:18    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)<br/>
20:33:18    at hudson.remoting.Channel.call(Channel.java:752)<br/>
20:33:18    ... 6 more<br/>
20:33:18 Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Invalid object ID 2 iota=14<br/>
20:33:18    at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:75)<br/>
20:33:18    at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)<br/>
20:33:18    at hudson.remoting.RemoteClassLoader.findResource(RemoteClassLoader.java:373)<br/>
20:33:18    at java.lang.ClassLoader.getResource(Unknown Source)<br/>
20:33:18    at org.jvnet.winp.Native.load(Native.java:85)<br/>
20:33:18    at org.jvnet.winp.Native.<clinit>(Native.java:56)<br/>
20:33:18    at org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java:212)<br/>
20:33:18    at hudson.util.ProcessTree$Windows.<clinit>(ProcessTree.java:469)<br/>
20:33:18    at hudson.util.ProcessTree.get(ProcessTree.java:328)<br/>
20:33:18    at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:953)<br/>
20:33:18    at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:944)<br/>
20:33:18    at hudson.remoting.UserRequest.perform(UserRequest.java:121)<br/>
20:33:18    at hudson.remoting.UserRequest.perform(UserRequest.java:49)<br/>
20:33:18    at hudson.remoting.Request$2.run(Request.java:324)<br/>
20:33:18    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
20:33:18    at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
20:33:18    at java.lang.Thread.run(Unknown Source)<br/>
20:33:18 Caused by: java.lang.IllegalStateException: Invalid object ID 2 iota=14<br/>
20:33:18    at hudson.remoting.ExportTable.diagnoseInvalidId(ExportTable.java:348)<br/>
20:33:18    at hudson.remoting.ExportTable.get(ExportTable.java:324)<br/>
20:33:18    at hudson.remoting.Channel.getExportedObject(Channel.java:604)<br/>
20:33:18    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:311)<br/>
20:33:18    at hudson.remoting.Request$2.run(Request.java:324)<br/>
20:33:18    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)<br/>
20:33:18    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
20:33:18    at java.lang.Thread.run(Thread.java:744)<br/>
20:33:18    at ......remote call to channel(Native Method)<br/>
20:33:18    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)<br/>
20:33:18    at hudson.remoting.Request.call(Request.java:171)<br/>
20:33:18    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:176)<br/>
20:33:18    at com.sun.proxy.$Proxy5.writeJarTo(Unknown Source)<br/>
20:33:18    at hudson.remoting.FileSystemJarCache.retrieve(FileSystemJarCache.java:66)<br/>
20:33:18    at hudson.remoting.JarCacheSupport$1.run(JarCacheSupport.java:62)<br/>
20:33:18    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
20:33:18    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:104)<br/>
20:33:18    ... 1 more<br/>
20:33:18 Caused by: java.lang.Exception: Object was recently deallocated<br/>
20:33:18     #2 (ref.0) : <span class="error">&#91;hudson.remoting.JarLoader&#93;</span><br/>
20:33:18       Created at Wed Dec 24 20:28:20 MSK 2014<br/>
20:33:18at hudson.remoting.ExportTable$Entry.<init>(ExportTable.java:93)<br/>
20:33:18at hudson.remoting.ExportTable.export(ExportTable.java:299)<br/>
20:33:18at hudson.remoting.Channel.internalExport(Channel.java:600)<br/>
20:33:18at hudson.remoting.Channel.export(Channel.java:591)<br/>
20:33:18at hudson.remoting.Channel.<init>(Channel.java:472)<br/>
20:33:18at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:280)<br/>
20:33:18at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:290)<br/>
20:33:18at org.jenkinsci.remoting.nio.NioChannelBuilder.build(NioChannelBuilder.java:36)<br/>
20:33:18at org.jenkinsci.remoting.nio.NioChannelBuilder.build(NioChannelBuilder.java:52)<br/>
20:33:18at jenkins.slaves.JnlpSlaveAgentProtocol$Handler.jnlpConnect(JnlpSlaveAgentProtocol.java:120)<br/>
20:33:18at jenkins.slaves.DefaultJnlpSlaveReceiver.handle(DefaultJnlpSlaveReceiver.java:63)<br/>
20:33:18at jenkins.slaves.JnlpSlaveAgentProtocol2$Handler2.run(JnlpSlaveAgentProtocol2.java:57)<br/>
20:33:18at jenkins.slaves.JnlpSlaveAgentProtocol2.handle(JnlpSlaveAgentProtocol2.java:31)<br/>
20:33:18at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:156)<br/>
20:33:18       Released at Wed Dec 24 20:28:20 MSK 2014<br/>
20:33:18at hudson.remoting.ExportTable$Entry.release(ExportTable.java:125)<br/>
20:33:18at hudson.remoting.ExportTable.unexportByOid(ExportTable.java:376)<br/>
20:33:18at hudson.remoting.Channel.unexport(Channel.java:612)<br/>
20:33:18at hudson.remoting.UnexportCommand.execute(UnexportCommand.java:38)<br/>
20:33:18at hudson.remoting.Channel$2.handle(Channel.java:483)<br/>
20:33:18at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)<br/>
20:33:18at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:597)<br/>
20:33:18at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>
20:33:18at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
20:33:18at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)<br/>
20:33:18at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)<br/>
20:33:18at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>
20:33:18at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
20:33:18at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
20:33:18at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
20:33:18at java.lang.Thread.run(Thread.java:744)<br/>
20:33:18     Caused by: Command hudson.remoting.UnexportCommand@1787906e created at<br/>
20:33:18at hudson.remoting.Command.<init>(Command.java:67)<br/>
20:33:18at hudson.remoting.Command.<init>(Command.java:50)<br/>
20:33:18at hudson.remoting.UnexportCommand.<init>(UnexportCommand.java:33)<br/>
20:33:18at hudson.remoting.RemoteInvocationHandler.finalize(RemoteInvocationHandler.java:234)<br/>
20:33:18at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)<br/>
20:33:18at java.lang.ref.Finalizer.runFinalizer(Unknown Source)<br/>
20:33:18at java.lang.ref.Finalizer.access$100(Unknown Source)<br/>
20:33:18at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)<br/>
20:33:18    at hudson.remoting.ExportTable.diagnoseInvalidId(ExportTable.java:341)<br/>
20:33:18    at hudson.remoting.ExportTable.get(ExportTable.java:324)<br/>
20:33:18    at hudson.remoting.Channel.getExportedObject(Channel.java:604)<br/>
20:33:18    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:311)<br/>
20:33:18    at hudson.remoting.Request$2.run(Request.java:324)<br/>
20:33:18    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)<br/>
20:33:18    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
20:33:18    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
20:33:18    at java.lang.Thread.run(Thread.java:744)<br/>
20:33:18 Caused by:   Released at Wed Dec 24 20:28:20 MSK 2014<br/>
20:33:18    at hudson.remoting.ExportTable$Entry.release(ExportTable.java:125)<br/>
20:33:18    at hudson.remoting.ExportTable.unexportByOid(ExportTable.java:376)<br/>
20:33:18    at hudson.remoting.Channel.unexport(Channel.java:612)<br/>
20:33:18    at hudson.remoting.UnexportCommand.execute(UnexportCommand.java:38)<br/>
20:33:18    at hudson.remoting.Channel$2.handle(Channel.java:483)<br/>
20:33:18    at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)<br/>
20:33:18    at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:597)<br/>
20:33:18    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>
20:33:18    at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
20:33:18    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)<br/>
20:33:18    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)<br/>
20:33:18    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>
20:33:18    ... 4 more<br/>
20:33:18 Caused by: Command hudson.remoting.UnexportCommand@1539730b created at<br/>
20:33:18    at hudson.remoting.Command.<init>(Command.java:67)<br/>
20:33:18    at hudson.remoting.Command.<init>(Command.java:50)<br/>
20:33:18    at hudson.remoting.UnexportCommand.<init>(UnexportCommand.java:33)<br/>
20:33:18    at hudson.remoting.RemoteInvocationHandler.finalize(RemoteInvocationHandler.java:234)<br/>
20:33:18    at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)<br/>
20:33:18    at java.lang.ref.Finalizer.runFinalizer(Unknown Source)<br/>
20:33:18    at java.lang.ref.Finalizer.access$100(Unknown Source)<br/>
20:33:18    at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)<br/>
</code></p>

<p>Statistically, one from 10 slaves break connection with such error.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=svchipiga" class="user-hover" rel="svchipiga">svchipiga</a> your problem (<tt>IllegalStateException: Invalid object ID 2 iota=14</tt>) looks unrelated and should be filed separately.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally duplicated by: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-06-a2/issues?q=in%3Atitle%20JENKINS-15796">JENKINS-15796</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-06-a2/issues?q=in%3Atitle%20JENKINS-25316">JENKINS-25316</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-06-a2/issues?q=in%3Atitle%20JENKINS-36991">JENKINS-36991</a>]</i>
