### ISSUE TITLE
[JENKINS-66527] intermittent NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#9149]
<p>About half of the times Jenkins fails to start.</p>

<p>The web UI displays:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-none">
java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer
  at jenkins.model.Jenkins.createComputer(Jenkins.java:3222)
  at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:162)
  at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:148)
  at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:48)
  at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:254)
  at hudson.model.Queue._withLock(Queue.java:1398)
  at hudson.model.Queue.withLock(Queue.java:1274)
  at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:240)
  at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1670)
  at jenkins.model.Jenkins.<init>(Jenkins.java:1023)
  at hudson.model.Hudson.<init>(Hudson.java:86)
  at hudson.model.Hudson.<init>(Hudson.java:82)
  at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
  at hudson.WebAppMain$3.run(WebAppMain.java:312)
</pre>
</div></div>

<p>The log contains dozens of exceptions and stacktraces.</p>

<p>Restarting often resolves the problem until the next time the service is restarted.</p>

<p>This occurred after upgrading from 2.263.3 to 2.303.1</p>

<p>The server was already running with OpenJDK11. That has not changed.</p>

<p> </p>

<p>Even a successful start results in 82345 lines of logging including 86 to 279 exceptions</p>

---
<details><summary><i>Originally reported by <a title="Bram Mertens" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=bram_mertens">bram_mertens</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-66527" target="_blank">intermittent NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer</a></i></summary>
<i><ul>
<li><b>reported by</b>: bram_mertens
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-03-07T12:27:08+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-06
</ul></i>
</details>
