### ISSUE TITLE
[JENKINS-15120] Minimize round trips for slave class loading

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#12023]
<p>Currently each attempt to load a class in a remote JVM makes a round-trip request to the master, which over a laggy network can make class loading quite slow, thus adding considerable overhead to the first build on a new slave.</p>

<p>Two possible solutions have been put forward.</p>

<h2><a name="Optimisticprefetch"></a>Optimistic prefetch</h2>

<p>The idea: when sending a class file to be loaded, scan its bytecode for other statically linked classes which have not yet been loaded, and send those along as well. In the common case that a network of classes is loaded around the same time, this would avoid some round trips.</p>

<h3><a name="Details"></a>Details</h3>

<p>The first part is for one side to keep track of what classes the other side has already loaded (into which class loader), which is basically memorizing the response from <tt>IClassLoader.fetch2</tt>.</p>

<p>The second part is to add <tt>Collection<ClassFile> IClassLoader.fetch3</tt> that works like <tt>fetch2</tt>, except it will also parse the class, figure out some of the referenced classes that are not yet loaded by the other side, then send them along.</p>

<p>Those prefetched class files would need to be remembered by <tt>RemoteClassLoader</tt> so that when those are actually requested it can load a class in the right classloader without calling back <tt>RemoteClassLoader.proxy</tt>. (Assuming there are no side effects, it could also eagerly call <tt>RemoteClassLoader.loadClassFile</tt> on the prefetched classes.)</p>

<p>The remoting layer supports talking to an earlier version of the remoting layer. We do this by a bitmask in <tt>Capability</tt>, so this needs one more bit defined there. There is no point in tracking the classes the other side has loaded if the other side will never call <tt>fetch3</tt>.</p>

<h2><a name="Bulktransfer"></a>Bulk transfer</h2>

<p>Send entire JAR files at a time, rather than individual classes; can wind up transferring more than is needed, but the reduction in latency is probably worth it. Since arbitrary class loader graphs might be in use, not just a flat classpath, some custom code needs to be run <em>remotely</em> which will implement the class loader delegation model without hitting the network for each class.</p>

<h3><a name="Details"></a>Details</h3>

<p>An API sketch:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">class </span>Channel {
  void setClassLoaderTrafficCop(TrafficCop cop);
}
<span class="code-keyword">interface</span> TrafficCop {
  <span class="code-comment">/** <span class="code-keyword">do</span> I know/control/own <span class="code-keyword">this</span> classloader? */</span>
  <span class="code-object">boolean</span> controls(<span class="code-object">ClassLoader</span> cl);
  Set<JarFile> getJarFilesOf(<span class="code-object">ClassLoader</span> cl);
  RemotePartOfTrafficCop getRemotePart();
}
<span class="code-keyword">class </span>JarFile {
  <span class="code-object">String</span> checksum();
  InputStream data();
}
<span class="code-comment">/** runs in remote agent */</span>
<span class="code-keyword">interface</span> RemotePartOfTrafficCop <span class="code-keyword">implements</span> Serializable {
  <span class="code-comment">/** given a <span class="code-keyword">class/</span>resource and an originating loader, what is the defining loader? */</span>
  RemoteClassLoader trafficControl(RemoteClassLoader origin, <span class="code-object">String</span> resourceName);
}
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-15120" target="_blank">Minimize round trips for slave class loading</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kohsuke Kawaguchi" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>
<li><b>reported by</b>: jglick
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-06-25T22:26:05+00:00
<li><b>votes</b>: 2
<li><b>watchers</b>: 12
<li><b>imported</b>: 2025-11-07
</ul></i>
</details>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Jesse Glick<br/>
Path:<br/>
 src/main/java/hudson/remoting/Channel.java<br/>
<a href="http://jenkins-ci.org/commit/remoting/2b1ec8ab152805f01b4063dabc4dcdef64421fed" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/remoting/2b1ec8ab152805f01b4063dabc4dcdef64421fed</a><br/>
Log:<br/>
  <a href="https://issues.jenkins.io/browse/JENKINS-15120" title="Minimize round trips for slave class loading" class="issue-link" data-issue-key="JENKINS-15120"><del>JENKINS-15120</del></a> Kohsuke’s explanation of why preloadJar does not really help.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p><a href="https://github.com/jenkinsci/remoting/pull/10" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/pull/10</a></p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p><a href="https://github.com/jenkinsci/mock-slave-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/mock-slave-plugin</a> useful for testing impact on performance more controllably than simply connecting to some node in the cloud.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>Using <tt>mock-slave</tt> with 10ms latency and building a multimodule Maven project in current trunk I get</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>223.8</td>
<td class='confluenceTd'>2993</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.7</td>
<td class='confluenceTd'>23</td>
</tr>
</tbody></table>
</div>


<p>With <tt>prefetch-JENKINS&#45;15120</tt> from Jenkins core checked out (which pulls in a branch of the same name from <tt>remoting</tt>), this was</p>

<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>Loading Type</th>
<th class='confluenceTh'>Time (s)</th>
<th class='confluenceTh'>Count</th>
</tr>
<tr>
<td class='confluenceTd'>Classes</td>
<td class='confluenceTd'>165.5</td>
<td class='confluenceTd'>3361 (prefetch cache: 1651)</td>
</tr>
<tr>
<td class='confluenceTd'>Resources</td>
<td class='confluenceTd'>2.3</td>
<td class='confluenceTd'>26</td>
</tr>
</tbody></table>
</div>


<p>though timing is not exactly comparable since the branch currently enables rather verbose logging which slows down the connection.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Kohsuke Kawaguchi<br/>
Path:<br/>
 src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java<br/>
 src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java<br/>
<a href="http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/maven-hpi-plugin/603535119122e820751607812bb7d0bd3b8c3556</a><br/>
Log:<br/>
  Modified to produce a jar file instead of WEB-INF/classes</p>

<p>Because of the prefetching change in remoting  (see <a href="https://issues.jenkins.io/browse/JENKINS-15120" title="Minimize round trips for slave class loading" class="issue-link" data-issue-key="JENKINS-15120"><del>JENKINS-15120</del></a>), it<br/>
is desirable now to produce class files in a jar file, not in a classes<br/>
directory, so that slaves can prefetch them and cache them efficiently.</p>


<p>Compare: <a href="https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/maven-hpi-plugin/compare/4d27f2880fa5...603535119122</a></p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<blockquote><p>Would this work affect freestyle projects using ant / nant / batch builds?</p></blockquote>

<p>Some, though not as much as for Maven projects. Depends on the plugins in use during the build, particularly how large their transitive dependencies are.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>:</i>
<p>Seems that this new feature breaks class loading of the findbugs plug-in, see <a href="https://issues.jenkins.io/browse/JENKINS-18405" title="Findbugs plugin unable to run on slaves with 1.519" class="issue-link" data-issue-key="JENKINS-18405"><del>JENKINS-18405</del></a> and <a href="https://issues.jenkins.io/browse/JENKINS-18394" title="IncompatibleClassChangeError after upgrade to 1.519" class="issue-link" data-issue-key="JENKINS-18394"><del>JENKINS-18394</del></a> for details...</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kutzi">kutzi</a>:</i>
<p>Maybe also the cause of <a href="https://issues.jenkins.io/browse/JENKINS-18401" title="java.lang.NoClassDefFoundError: hudson/maven/MavenReporter" class="issue-link" data-issue-key="JENKINS-18401"><del>JENKINS-18401</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>:</i>
<p>Reopening this issue since it breaks class loading of findbugs plug-in and maven jobs. I can reproduce that issue on my machine, is there anything I can add in my plug-in to prevent these incompatible class exceptions?</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>:</i>
<p>Process wise, let's leave this bug closed. Instead, if you come across bugs that appear to be related, please link them.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=yyuu">yyuu</a>:</i>
<p>This also affects plugins written in JRuby. I created the issue of ruby plugins as <a href="https://issues.jenkins.io/browse/JENKINS-18528" title="ruby plugins cannot work on Jenkins 1.519+" class="issue-link" data-issue-key="JENKINS-18528"><del>JENKINS-18528</del></a></p>
