### ISSUE TITLE
[JENKINS-11420] JDK Auto install throws FATAL: org/apache/xml/utils/PrefixResolver

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#11276]
<p>It appears that JDK auto install has been broken since version 1.433.  It last worked on version 1.432.  Below is the error that you get when it tries to auto install the JDK.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Installing JDK jdk-6u24-oth-JPR
Downloading JDK from http:<span class="code-comment">//download.oracle.com/otn/java/jdk/6u24-b07//jdk-6u24-windows-x64.exe
</span>FATAL: org/apache/xml/utils/PrefixResolver
java.lang.NoClassDefFoundError: org/apache/xml/utils/PrefixResolver
	at com.gargoylesoftware.htmlunit.html.DomNamespaceNode.getLocalName(DomNamespaceNode.java:81)
	at com.gargoylesoftware.htmlunit.html.HtmlElement.getNodeName(HtmlElement.java:308)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.addNodeToRightParent(HTMLParser.java:636)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.startElement(HTMLParser.java:610)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.cyberneko.html.HTMLTagBalancer.callStartElement(HTMLTagBalancer.java:1126)
	at org.cyberneko.html.HTMLTagBalancer.startElement(HTMLTagBalancer.java:734)
	at org.cyberneko.html.filters.DefaultFilter.startElement(DefaultFilter.java:136)
	at org.cyberneko.html.filters.NamespaceBinder.startElement(NamespaceBinder.java:278)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2697)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2013)
	at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:907)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:901)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:350)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:304)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:134)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:101)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:449)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:332)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:389)
	at hudson.tools.JDKInstaller.locate(JDKInstaller.java:369)
	at hudson.tools.JDKInstaller.performInstallation(JDKInstaller.java:125)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:61)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:107)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:150)
	at hudson.model.JDK.forNode(JDK.java:112)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:822)
	at hudson.maven.AbstractMavenBuild.getEnvironment(AbstractMavenBuild.java:59)
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:155)
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:673)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1193)
	at hudson.model.AbstractBuild$AbstractRunner.checkout(AbstractBuild.java:567)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:455)
	at hudson.model.Run.run(Run.java:1404)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:470)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:230)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.utils.PrefixResolver
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
	at winstone.classLoader.WebappClassLoader.loadClass(WebappClassLoader.java:83)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
	... 40 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jim McCaskey" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jmccaske">jmccaske</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-11420" target="_blank">JDK Auto install throws FATAL: org/apache/xml/utils/PrefixResolver</a></i></summary>
<i><ul>
<li><b>reported by</b>: jmccaske
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2011-10-31T02:02:47+00:00
<li><b>votes</b>: 5
<li><b>watchers</b>: 7
<li><b>imported</b>: 2025-11-07
</ul></i>
</details>
