### ISSUE TITLE
[JENKINS-10696] Problem with libpam4j after 1.420

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#11149]
<p>When I upgrade from 1.420 to a newer version (including 1.425, just now) and attempt to load Jenkins after restart, I get this stack trace in jenkins.log:</p>

<p><span class="error">&#91;Winstone 2011/08/12 13:41:49&#93;</span> - Untrapped Error in Servlet<br/>
java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.libpam.impl.CLibrary<br/>
	at org.jvnet.libpam.UnixUser.exists(UnixUser.java:116)<br/>
	at hudson.security.PAMSecurityRealm.loadUserByUsername(PAMSecurityRealm.java:93)<br/>
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.loadUserDetails(TokenBasedRememberMeServices.java:308)<br/>
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.autoLogin(TokenBasedRememberMeServices.java:218)<br/>
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:104)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br/>
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:66)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)<br/>
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)<br/>
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)<br/>
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)<br/>
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)<br/>
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)<br/>
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)<br/>
	at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)<br/>
	at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:244)<br/>
	at winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)<br/>
	at java.lang.Thread.run(Thread.java:662)</p>

<p>Security settings:<br/>
  Security realm: Unix user/group database<br/>
  Access control service name: sshd<br/>
  Authorization: logged-in users can do anything</p>

<p>I did <b>not</b> explicitly log out from the 1.420 install before upgrading.</p>

---
<details><summary><i>Originally reported by <a title="Craig Cottingham" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=craigcottingham">craigcottingham</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-10696" target="_blank">Problem with libpam4j after 1.420</a></i></summary>
<i><ul>
<li><b>reported by</b>: craigcottingham
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2022-11-23T19:39:58+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-07
</ul></i>
</details>
