### ISSUE TITLE
[JENKINS-787] a number of classes not found in v 1.135

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#1966]
<p>after upgrading from 1.132  to 1.135 most of hudson instances are not able to<br/>
start due to missing classes. </p>

<p>java.lang.NoClassDefFoundError: com/thoughtworks/xstream/core/JVM<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:50)</p>

<p>.....</p>

<p>java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildException<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:127)<br/>
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)<br/>
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)<br/>
	at winstone.HostConfiguration.(HostConfiguration.java:73)<br/>
....<br/>
java.lang.NoClassDefFoundError: org/jfree/chart/axis/CategoryAxis<br/>
	at hudson.model.Items.(Items.java:27)<br/>
	at hudson.model.Hudson.(Hudson.java:236)<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:105)<br/>
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)<br/>
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)<br/>
	at winstone.HostConfiguration.(HostConfiguration.java:73)<br/>
	at winstone.HostGroup.initHost(HostGroup.java:85)</p>

---
<details><summary><i>Originally reported by <a title="eirikma" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=eirikma">eirikma</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-787" target="_blank">a number of classes not found in v 1.135</a></i></summary>
<i><ul>
<li><b>reported by</b>: eirikma
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2007-09-04T11:04:53+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 0
<li><b>imported</b>: 2025-11-06
</ul></i>
</details>
