### ISSUE TITLE
[JENKINS-19345] NoClassDefFoundError on project build

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#6929]
<p>I have several free style projects, some of then run on a scheduled basis and some of them using a post commit hook from Github.<br/>
After upgrading to version 1.528 and updating the installed plugins, the automatic some manual builds and all automatic builds started failing, apart from that, another exception it's raised when trying to open the changelog for a build. Here are the exceptions:</p>

<p>1) On the builds that fail here is the exception log:<br/>
tarted by user Federico Saravia<br/>
Building in workspace /var/lib/jenkins/jobs/test-api/workspace<br/>
Checkout:workspace / /var/lib/jenkins/jobs/test-api/workspace - hudson.remoting.LocalChannel@6281d31b<br/>
Using strategy: Default<br/>
Last Built Revision: Revision e87ed66aeab0ed5b9da96c574c3c326e4a70e332 (origin/development)<br/>
Fetching changes from 1 remote Git repository<br/>
Fetching upstream changes from origin<br/>
Commencing build of Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)<br/>
Checking out Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)<br/>
FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)<br/>
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)<br/>
	... 12 more</p>

<p>On the changelog screen the raised Exception is different (only if there has been changes in the build), the exception is attached.</p>

<p>Another thing, maybe related to the issue is that jenkins tells me that I have old or unreadable data: <br/>
hudson.model.FreeStyleProject	api	NoClassDefFoundError: hudson/tasks/Mailer$UserProperty</p>

<p>I can delete that data, but every time one of the builds fail it comes back.<br/>
I may point that I never installed or used the Mailer plugin. The only plugins I installed and use are the Git plugin and the SSH plugin, so I don't know where this Mailer$UserProperty came from.</p>

<p>I already tried downgrading the plugins to their bundled version but that didn's solve the problem</p>

**Attachments:**

- [Exception on changes screen.txt](https://issues.jenkins.io/secure/attachment/24243/Exception on changes screen.txt)

---
<details><summary><i>Originally reported by <a title="Federico Saravia" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fedesaravia">fedesaravia</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-19345" target="_blank">NoClassDefFoundError on project build</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Nicolas De Loof" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof">ndeloof</a>
<li><b>reported by</b>: fedesaravia
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-10-16T12:25:21+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 9
<li><b>imported</b>: 2025-11-06
</ul></i>
</details>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=beardyjay">beardyjay</a>:</i>
<p>Have ran into the same issue however I am running Jenkins 1.529. Same situation, some manual builds will work however all polled builds fail every time. I do not have the mailer plugin installed and its not within the plugin directory on disk. </p>

<p>OS: Redhat 6.4 <br/>
Jenkins: 1.529<br/>
Git Plugin: 1.5.0<br/>
Git Client Plugin: 1.1.2</p>

<p>Please let me know if you need more information. </p>


<p>Fetching upstream changes from origin<br/>
Commencing build of Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)<br/>
Checking out Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)<br/>
FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:49)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)<br/>
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)<br/>
	... 12 more</p>


<p>FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:896)<br/>
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:420)<br/>
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:417)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:733)<br/>
	at hudson.model.Run.execute(Run.java:1628)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=beardyjay">beardyjay</a>:</i>
<p>Federico, </p>

<p>Thanks for that, I have enabled the mailer plugin and that has fixed the issue for me. </p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kwin">kwin</a>:</i>
<p>We are running exactly into that issue with the git-plugin 2.0.3. But it works with 2.0.1. So there must be a regression bug in 2.0.3. The weird thing is, that we indeed have the mailer plugin installed and still run into that error with git-plugin 2.0.3</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:80)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:74)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:51)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:29)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:903)
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:877)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:413)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:410)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:710)
	at hudson.model.Run.execute(Run.java:1690)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:246)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 13 more
</pre>
</div></div>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=tanis">tanis</a>:</i>
<p>@Graham Hay I tried what you suggested but I still get the same error every time the GIT plugin updates from the origin repo.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally duplicated by: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-06-a2/issues?q=in%3Atitle%20JENKINS-22115">JENKINS-22115</a>]</i>
