### ISSUE TITLE
[JENKINS-26575] Running the reverse migrator after upgrading to 1.597 throws NoClassDefFoundError: javax/servlet/http/HttpServletRequest

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-06-a2#5301]
<p>After upgrading to 1.597 from 1.588 on Windows </p>
<ul>
	<li>I cannot downgrade because trying to run the unmigrate script fails with:
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Exception in thread <span class="code-quote">"main"</span> java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
at hudson.Util.createSymlinkJava7(Util.java:1224)
at hudson.Util.createSymlink(Util.java:1118)
at jenkins.model.RunIdMigrator.unmigrateBuildsDir(RunIdMigrator.java:371
)
at jenkins.model.RunIdMigrator.unmigrateJobsDir(RunIdMigrator.java:320)
at jenkins.model.RunIdMigrator.main(RunIdMigrator.java:307)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
... 5 more
</pre>
</div></div></li>
</ul>

---
<details><summary><i>Originally reported by <a title="David Light" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dhlight">dhlight</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-26575" target="_blank">Running the reverse migrator after upgrading to 1.597 throws NoClassDefFoundError: javax/servlet/http/HttpServletRequest</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>
<li><b>reported by</b>: dhlight
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2025-03-25T17:58:25+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-06
</ul></i>
</details>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dhlight">dhlight</a>:</i>
<p>Easy tracking if you happen to search for that specific portion of the error. That error is still searchable in the description and you've made it unreadable as a title</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>Well this is the critical and identifying aspect of the error. There could be all sorts of unrelated problems running the reverse migrator.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=sakshisood">sakshisood</a>:</i>
<p>I am also facing the same issue.</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=sakshisood">sakshisood</a>:</i>
<p>I am downgrading the version from 2.7.4 to 1.580.3 on linux ,I have also faced the same error but below command resolved this error:</p>

<p>java -classpath "/root/.jenkins/war/WEB-INF/lib/jenkins-core-2.7.4.jar:/root/.jenkins/war/WEB-INF/commons-io-2.4.jar:/root/.jenkins/war/WEB-INF/lib/stapler-1.243.jar:/root/.jenkins/war/WEB-INF/lib/ant-1.8.4.jar:/root/.jenkins/war/WEB-INF/lib/commons-lang-2.6.jar:/root/.jenkins/war/winstone.jar" jenkins.model.RunIdMigrator "/root/.jenkins"</p>

<p>But, after starting Jenkins 1.580.3 I still cannot see job history , any idea?</p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=JIRAUSER159232">JIRAUSER159232</a>:</i>
<p>This Jira can be closed as the unmigrate functionality was removed in <a href="https://github.com/jenkinsci/jenkins/pull/9092" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/9092</a></p>

**Comment by jenkins-infra-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>Thanks!</p>
